import React, { useEffect, useMemo, useState } from 'react'
import { useDispatch } from 'react-redux';
import { CircularProgress, IconButton, Typography } from '@mui/material';
import { downloadQrImageApi, FetchQrDetailsApi } from '../../apis/inventoryLogs.api';
import { callApiAction } from '../../store/actions/commonAction';
import moment from 'moment';
import { findObjectKeyByValue } from '../../utils/main';
import { LOG_TYPE, MATERIAL_TYPE, SNACK_BAR_VARIETNS } from '../../utils/constants';
import GenerateQrListUi from './GenerateQrListUi';
import { useCallback } from 'react';
import { Download } from '@mui/icons-material';
import { saveAs } from 'file-saver';
import { callSnackBar } from '../../store/actions/snackbarAction';

const ActionComponent = ({ params, setParams }) => {
  const dispatch = useDispatch()
  const [downloadLoading, setDownloadLoading] = useState(false)

  const handleQrImageDownload = async () => {
    setDownloadLoading(true);
    try {
      const response = await downloadQrImageApi({ _id: params._id });
      const qrImageBlob = response.data;
      const filename = `Inventory-QR.png`;
      saveAs(qrImageBlob, filename);
    } catch (downloadError) {
      dispatch(callSnackBar("Cannot Download QR", SNACK_BAR_VARIETNS.error))
    } finally {
      setDownloadLoading(false);
    }
  };

  return (
    <IconButton onClick={handleQrImageDownload} disabled={downloadLoading}>
      {downloadLoading ? (
        <CircularProgress size={24} />
      ) : (
        <Download sx={{ color: "#255766" }} />
      )}
    </IconButton>
  )
};


const GenerateQrListController = () => {
  const dispatch = useDispatch()
  const [list, setList] = useState({})
  const [loading, setLoading] = useState(false)

  const columns = useMemo(
    () => [
      {
        id: 1,
        fieldName: "",
        label: "Date",
        align: "left",
        sort: true,
        renderValue: (params, setParams) => moment(params?.date).format("DD/MM/YYYY"),
      },
      {
        id: 2,
        fieldName: "",
        label: "Material Type",
        align: "left",
        sort: true,
        renderValue: (params, setParams) => findObjectKeyByValue(params?.materialType, MATERIAL_TYPE),
      },
      {
        id: 3,
        fieldName: "",
        label: "Material Name",
        align: "left",
        sort: true,
        renderValue: (params, setParams) => params?.materialId?.name,
      },
      {
        id: 4,
        fieldName: "",
        label: "Amount",
        align: "left",
        sort: true,
        renderValue: (params, setParams) => params?.amount,
      },
      {
        id: 5,
        fieldName: "",
        label: "Quantity",
        align: "left",
        sort: true,
        renderValue: (params, setParams) => params?.quantity,
      },
      {
        id: 6,
        fieldName: "",
        label: "Vendor",
        align: "left",
        sort: true,
        renderValue: (params, setParams) => params?.vendorId?.name,
      },
      {
        id: 8,
        fieldName: "",
        label: "Generated By",
        align: "left",
        sort: true,
        renderValue: (params, setParams) => params?.generatedBy?.name,
      },
      {
        id: 9,
        fieldName: "",
        label: "Used By",
        align: "left",
        sort: true,
        renderValue: (params, setParams) => params?.usedBy?.name ?? "NA",
      },
      {
        id: 10,
        fieldName: "",
        label: "Already Used",
        align: "left",
        sort: true,
        renderValue: (params, setParams) => params?.isUsed ? "Yes" : "No",
      },
      {
        id: 7,
        fieldName: "",
        label: "Log Type",
        align: "left",
        sort: true,
        renderValue: (params, setParams) => <Typography color={"white"} sx={{ backgroundColor: "#255766", width: "4vw", borderRadius: "5px", display: "flex", justifyContent: "center" }}>{findObjectKeyByValue(params?.logType, LOG_TYPE)}</Typography>,
      },
      // {
      //   id: 12,
      //   fieldName: "",
      //   label: "QR Code",
      //   align: "left",
      //   sort: true,
      //   renderValue: (params, setParams) => <img src={params?.qrCode} alt="QR Code" style={{ width: "50px", height: "50px" }} />,
      // },
      {
        id: 11,
        fieldName: "",
        label: "Action",
        align: "left",
        sort: true,
        renderValue: (params, setParams) => (
          <ActionComponent
            params={params}
            setParams={setParams}
          />
        ),
      },
    ],
    []
  );

  const [filters, setFilters] = useState({
    pageNo: 1,
    pageSize: 10,
    search: "",
    searchable: ["name"],
    sort: "",
    sortDirection: -1,
  });


  const fetchList = useCallback(() => {
    setLoading(true);
    dispatch(
      callApiAction(
        async () => await FetchQrDetailsApi({ ...filters }),
        (response) => {
          setList(response);
          setLoading(false);
        },
        (err) => {
          setLoading(false);
        }
      )
    );
  }, [dispatch, filters]);
  useEffect(() => {
    fetchList();
  }, [filters, fetchList]);

  return (
    <GenerateQrListUi
      list={list}
      setList={setList}
      loading={loading}
      filters={filters}
      columns={columns}
      setFilters={setFilters}
      fetchList={fetchList}
    />
  )
}

export default GenerateQrListController