export const SOFTWARE_ACCESS = {
  IMS: 1,
  DMS: 2,
  RMS: 3,
};

export const USER_ROLES = {
  ADMIN: 1,
  ACCOUNT: 2,
  PURCHASE: 3,
  DESIGN_TEAM: 4,
  PRODUCTION: 5,
  PACKAGING_AND_DISPATCH: 6,

  ASSEMBLY: 7,
  QC_PACAKAGING: 8,
  QC_UAE: 9,

  HR: 10,
  INVENTORY: 11,
  ELECTRONIC: 12,
};

export const actions = {
  SIGN_IN: "SIGN_IN",
  SET_USER: "SET_USER",
  SIGN_OUT: "SIGN_OUT",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  UPDATE_USER_DATA: "UPDATE_USER_DATA",
  SET_USER_LAST_READ_NOTIFICATION: "SET_USER_LAST_READ_NOTIFICATION",
  CALL_SNACKBAR_DATA: "CALL_SNACKBAR_DATA",
  SET_NOTIFICATION_DATA: "SET_NOTIFICATION_DATA",
  NOTIFICATION_READ: "NOTIFICATION_READ",
  CONNECT_DEVICE: "CONNECT_DEVICE",
  DISCONNECT_DEVICE: "DISCONNECT_DEVICE",
  SET_DEVICE_VERSION: "SET_DEVICE_VERSION",

  FETCH_DATA_VENDER_LODING: "FETCH_DATA_VENDER_LODING",
  FETCH_DATA_VENDER_DATA: "FETCH_DATA_VENDER_DATA",
  FETCH_DATA_VENDER_DELETE: "FETCH_DATA_VENDER_DELETE",

  FETCH_DATA_RAWMATERIAL_LODING: "FETCH_DATA_RAWMATERIAL_LODING",
  FETCH_DATA_RAWMATERIAL_DATA: "FETCH_DATA_RAWMATERIAL_DATA",
  FETCH_DATA_RAWMATERIAL_DELETE: "FETCH_DATA_RAWMATERIAL_DELETE",

  FETCH_DATA_PRODUCT_LODING: "FETCH_DATA_PRODUCT_LODING",
  FETCH_DATA_PRODUCT_DATA: "FETCH_DATA_PRODUCT_DATA",
  FETCH_DATA_PRODUCT_DELETE: "FETCH_DATA_PRODUCT_DELETE",

  FETCH_DATA_DEPARTMENT_LODING: "FETCH_DATA_DEPARTMENT_LODING",
  FETCH_DATA_DEPARTMENT_DATA: "FETCH_DATA_DEPARTMENT_DATA",
  FETCH_DATA_DEPARTMENT_DELETE: "FETCH_DATA_DEPARTMENT_DELETE",

  FETCH_DATA_TYPE_OF_SALES_LODING: "FETCH_DATA_TYPE_OF_SALES_LODING",
  FETCH_DATA_TYPE_OF_SALES_DATA: "FETCH_DATA_TYPE_OF_SALES_DATA",
  FETCH_DATA_TYPE_OF_SALES_DELETE: "FETCH_DATA_TYPE_OF_SALES_DELETE",

  FETCH_DATA_CATEGORY_LODING: "FETCH_DATA_CATEGORY_LODING",
  FETCH_DATA_CATEGORY_DATA: "FETCH_DATA_CATEGORY_DATA",
  FETCH_DATA_CATEGORY_DELETE: "FETCH_DATA_CATEGORY_DELETE",

  FETCH_DATA_UPDATE_STOCK_PRODUCT_LODING:
    "FETCH_DATA_UPDATE_STOCK_PRODUCT_LODING",
  FETCH_DATA_UPDATE_STOCK_PRODUCT_DATA: "FETCH_DATA_UPDATE_STOCK_PRODUCT_DATA",
  FETCH_DATA_UPDATE_STOCK_PRODUCT_DELETE:
    "FETCH_DATA_UPDATE_STOCK_PRODUCT_DELETE",

  FETCH_DATA_UPDATE_STOCK_RAW_MATERIAL_LODING:
    "FETCH_DATA_UPDATE_STOCK_RAW_MATERIAL_LODING",
  FETCH_DATA_UPDATE_STOCK_RAW_MATERIAL_DATA:
    "FETCH_DATA_UPDATE_STOCK_RAW_MATERIAL_DATA",
  FETCH_DATA_UPDATE_STOCK_RAW_MATERIAL_DELETE:
    "FETCH_DATA_UPDATE_STOCK_RAW_MATERIAL_DELETE",

  FETCH_DATA_QUALITY_CHECK_LODING: "FETCH_DATA_QUALITY_CHECK_LODING",
  FETCH_DATA_QUALITY_CHECK_DATA: "FETCH_DATA_QUALITY_CHECK_DATA",
  FETCH_DATA_QUALITY_CHECK_DELETE: "FETCH_DATA_QUALITY_CHECK_DELETE",

  FETCH_BATCH_LODING: "FETCH_BATCH_LOADING",
  FETCH_BATCH_DATA: "FETCH_BATCH_DATA",
  FETCH_BATCH_DELETE: "FETCH_BATCH_DELETE",

  FETCH_DATA_PRODUCT_BRAND_LODING: "FETCH_DATA_PRODUCT_BRAND_LODING",
  FETCH_DATA_PRODUCT_BRAND_DATA: "FETCH_DATA_PRODUCT_BRAND_DATA",
  FETCH_DATA_PRODUCT_BRAND_DELETE: "FETCH_DATA_PRODUCT_BRAND_DELETE",

  FETCH_DATA_PRODUCT_COLOR_LODING: "FETCH_DATA_PRODUCT_COLOR_LODING",
  FETCH_DATA_PRODUCT_COLOR_DATA: "FETCH_DATA_PRODUCT_COLOR_DATA",
  FETCH_DATA_PRODUCT_COLOR_DELETE: "FETCH_DATA_PRODUCT_COLOR_DELETE",

  FETCH_DATA_PRODUCT_TYPE_LODING: "FETCH_DATA_PRODUCT_TYPE_LODING",
  FETCH_DATA_PRODUCT_TYPE_DATA: "FETCH_DATA_PRODUCT_TYPE_DATA",
  FETCH_DATA_PRODUCT_TYPE_DELETE: "FETCH_DATA_PRODUCT_TYPE_DELETE",

  FETCH_COMPONENT_LODING: "FETCH_COMPONENT_LODING",
  FETCH_COMPONENT_DATA: "FETCH_COMPONENT_DATA",
  FETCH_COMPONENT_DELETE: "FETCH_COMPONENT_DELETE",

  FETCH_ITEM_TYPE_LODING: "FETCH_ITEM_TYPE_LODING",
  FETCH_ITEM_TYPE_DATA: "FETCH_ITEM_TYPE_DATA",
  FETCH_ITEM_TYPE_DELETE: "FETCH_ITEM_TYPE_DELETE",

  FETCH_REJECTION_REASON_LODING: "FETCH_REJECTION_REASON_LODING",
  FETCH_REJECTION_REASON_DATA: "FETCH_REJECTION_REASON_DATA",
  FETCH_REJECTION_REASON_DELETE: "FETCH_REJECTION_REASON_DELETE",

  FETCH_INVENTORY_MASTER_LODING: "FETCH_INVENTORY_MASTER_LODING",
  FETCH_INVENTORY_MASTER_DATA: "FETCH_INVENTORY_MASTER_DATA",
  FETCH_INVENTORY_MASTER_DELETE: "FETCH_INVENTORY_MASTER_DELETE",

  SET_VERSION_DATA: "SET_VERSION_DATA",
  START_VERSION_LOADING: "START_VERSION_LOADING",
  SET_VERSION_DATA_ONDELETE: "SET_VERSION_DATA_ONDELETE ",

  SET_BTE_VOLUME: "SET_BTE_VOLUME",
  SET_BTE_MODE: "SET_BTE_MODE",
  SET_BTE_CURRENT_VOLUME: "SET_BTE_CURRENT_VOLUME",
  RESET_DEVICE_DATA_STORE: "RESET_DEVICE_DATA_STORE",

  SET_DEVICE_SELECTED: "SET_DEVICE_SELECTED",
  SET_DEVICE_MAC: "SET_DEVICE_MAC",
  SET_DEVICE_SIDE: "SET_DEVICE_SIDE",
  SET_DEVICE_CONNECT: "SET_DEVICE_CONNECT",
  CHANGE_WRITE_FUN: "CHANGE_WRITE_FUN",
  IS_AUDIO_CHECK: "IS_AUDIO_CHECK",

  SET_DEVICE_STORAGE: "SET_DEVICE_STORAGE",
  SET_BOX_DETAILS: "SET_BOX_DETAILS",
  SET_DEVICE_BOXID_DETAILS: "SET_DEVICE_BOXID_DETAILS",
  SET_DEVICE_COLOR_DETAILS: "SET_DEVICE_COLOR_DETAILS",

  SET_RIC_DATA: "SET_RIC_DATA",
  SET_VOLUME_LEVEL: "SET_VOLUME_LEVEL",
  CHANGE_RIC_MODE_RIGHT: "CHANGE_RIC_MODE_RIGHT",
  CHANGE_RIC_MODE_LEFT: "CHANGE_RIC_MODE_LEFT",

  SET_RIC8_VOLUME: "SET_RIC8_VOLUME",
  SET_RIC8_CURRENT_VOLUME: "SET_RIC8_CURRENT_VOLUME",

  SET_ITE_OPTIMA_CURRENT_VOLUME: "SET_ITE_OPTIMA_CURRENT_VOLUME",
  SET_ITE_OPTIMA_VOLUME: "SET_ITE_OPTIMA_VOLUME",

  SET_ITE_PRIME_MODE: "SET_ITE_PRIME_MODE",
  SET_ITE_PRIME_VOLUME: "SET_ITE_PRIME_VOLUME",
  SET_ITE_PRIME_CURRENT_VOLUME: "SET_ITE_PRIME_CURRENT_VOLUME",

  SET_SAFE_BUDS_TAP: "SET_SAFE_BUDS_TAP",
  SET_FOT_FILES_VERSION: "SET_FOT_FILES_VERSION",
  SET_FOT_FILES: "SET_FOT_FILES",
  SET_SAFE_BUDS_CURRENT_VOLUME: "SET_SAFE_BUDS_CURRENT_VOLUME",
  FETCH_VOLUME_SAFE_BUDS: "FETCH_VOLUME_SAFE_BUDS",
  FETCH_ISMIC_SAFE_BUDS: "FETCH_ISMIC_SAFE_BUDS",
  SET_QC_TEST_RESULT: "SET_QC_TEST_RESULT",
  SET_QC_TEST_CLOSE_RESULT: "SET_QC_TEST_CLOSE_RESULT",

  SET_STEP: "SET_STEP",
};

export const SERVICE_UUID = {
  1: "e093f3b5-00a3-a9e5-9eca-40016e0edc24",
  6: "0000fff0-0000-1000-8000-00805f9b34fb",
  8: "0000fff0-0000-1000-8000-00805f9b34fb",
  9: "0000fdc2-0000-1000-8000-00805f9b34fb",
  11: "0000fff0-0000-1000-8000-00805f9b34fb",
  12: "4157b00b-d129-aeb5-859b-d547e30ffcb1",
  13: "4157b00b-d129-aeb5-859b-d547e30ffcb1",
  15: "f6898c59-8e5a-4dc4-a8b5-01dd76388822",
};

export const MANUFACTURER_IDENTIFIER = {
  1: "0x0362",
  6: "0x6C42",
  8: "0x0088",
  9: "0x3231",
  11: "0x6C42",
  12: " 0x07E3",
  15: "0x0F4B",
  50: "0xB822",
  51: "0xFF12", // safeBuds
};

export const CHARACTERISTIC_UUID_READ_WRITE = {
  1: "e093f3b5-00a3-a9e5-9eca-40036e0edc24",
  6: "0000fff2-0000-1000-8000-00805f9b34fb",
  8: "0000fff2-0000-1000-8000-00805f9b34fb",
  9: "e49a25e0-f69a-11e8-8eb2-f2801f1b9fd1",
  11: "0000fff2-0000-1000-8000-00805f9b34fb",
  12: "4157b611-d129-aeb5-859b-d547e30ffcb1",
  13: "4157b611-d129-aeb5-859b-d547e30ffcb1",
  15: "866ca7ac-fae8-4753-a61b-8793a0ee26a0",
};

export const CHARACTERISTIC_UUID_READ_NOTIFY = {
  1: "e093f3b5-00a3-a9e5-9eca-40026e0edc24",
  6: "0000fff1-0000-1000-8000-00805f9b34fb",
  8: "0000fff1-0000-1000-8000-00805f9b34fb",
  9: "e49a28e1-f69a-11e8-8eb2-f2801f1b9fd1",
  11: "0000fff1-0000-1000-8000-00805f9b34fb",
  12: "4157b612-d129-aeb5-859b-d547e30ffcb1",
  13: "4157b612-d129-aeb5-859b-d547e30ffcb1",
  15: "866ca7ac-fae8-4753-a61b-8793a0ee26a0",
};

export const NOTIFICATION_TYPE = {
  general: "general",
  lead: "lead",
};

export const YES_NO = {
  Pass: true,
  Reject: false,
};

export const SNACK_BAR_VARIETNS = {
  error: "error",
  suceess: "success",
  info: "info",
  warning: "warning",
};

export const DAY_WEEK_MONTH = {
  DAY: "day",
  WEEK: "week",
};

export const LOG_TYPE = {
  In: 1,
  Out: -1,
};

export const DATE_TIME_FILTERS = {
  this_week: "This Week",
  this_month: "This Month",
  this_year: "This Year",
  last_month: "Last Month",
  last_year: "Last Year",
  last_week: "Last Week",
  today: "Today",
  yesterday: "Yesterday",
};

export const MATERIAL_TYPE = {
  RAW_MATERIALS: 1,
  SKD: 2,
  SFG: 3,
  FG: 4,
  // ITEM: 5,
};
export const MATERIAL_REQUEST_STATUS = {
  PENDING: 1,
  APPROVAL_1: 2,
  APPROVAL_2: 3,
  ALLOCATED: 4,
  REJECTED: 5,
};
export const GRN_TYPE = {
  STANDARD: 1,
  IQC_REJECTED: 2,
  RETURNED: 3,
};

export const STATUS_COLOR_TYPE = (currentstatus) => {
  switch (currentstatus) {
    case true:
      return "#255766";
    default:
      return "white";
  }
};

export const BUTTON_STATUS_COLOR_TYPE = (currentstatus) => {
  switch (currentstatus) {
    case true:
      return "contained";
    default:
      return "outlined";
  }
};

export const DEVICES_NAME = {
  1: "BTE OPTIMA",
  2: "BTE PRIME",
  // 3: "GLASSES",
  // 4: "BTE 32",
  // 5: "BTE 24",
  6: "RIC OPTIMA 16",
  // 7: "RIC PRIME",
  8: "RIC OPTIMA 8",
  9: "ITE OPTIMA",
  10: "POWER BTE",
  11: "RIC OPTIMA 32",
  12: "ITE PRIME",
  // 13: "NECKBAND",

  14: "WEHEAR OX",
  15: "SAFE BUDS",
  17: "WEHEAR 2.0",
};

export const LISTENING_SIDE = {
  LEFT: 1,
  RIGHT: 2,
  BOTH: 3,
};

export const DOM_TYPE = {
  OPEN: 1,
  CLOSE: 2,
  POWER: 3,
  EAR_MOLD: 4,
  TULIP: 5,
  VENTED: 6,
  STANDARD_DOM: 7,
};

export const DEVICES = {
  BTE_OPTIMA: 1,
  BTE_PRIME: 2,
  RIC_OPTIMA: 6,
  RIC_OPTIMA_8: 8,
  ITE_OPTIMA: 9,
  // POWER_BTE: 10,
  // RIC_32: 11,
  ITE_PRIME: 12,
  // NECKBAND: 13,

  WEHEAR_OX: 14,
  SAFE_BUDS: 15,
  // SAFE_HEADPHONE: 16,
  WEHEAR_2_0: 17,
};

export const QC_TEST_CASE = {
  FUNCTIONALITY_TEST: 1,
  APPEARANCE_TEST: 2,
  ACCESSORIES: 3,
  DEVICE_DETAILS: 4,
  LEFT_FUNCTIONALITY_TEST: 5,
  RIGHT_FUNCTIONALITY_TEST: 6,
  LEFT_APPEARANCE_TEST: 7,
  RIGHT_APPEARANCE_TEST: 8,
  LEFT_ACCESSORIES: 9,
  RIGHT_ACCESSORIES: 10,
  LEFT_DEVICE_DETAILS: 11,
  RIGHT_DEVICE_DETAILS: 12,
};

export const QC_TEST_CASE_BAND = {
  FUNCTIONALITY_TEST: 1,
  APPEARANCE_TEST: 2,
  ACCESSORIES: 3,
};

export const QC_TEST_CASE_HEARING_AID = {
  LEFT_FUNCTIONALITY_TEST: 1,
  LEFT_APPEARANCE_TEST: 2,
  ACCESSORIES: 3,
  RIGHT_FUNCTIONALITY_TEST: 4,
  RIGHT_APPEARANCE_TEST: 5,
};
export const CATEGORY = {
  HEARING_BAND: 1,
  HEARING_AID: 2,
};

export const COUNTRY_CATEGORY = {
  GENERAL: 8,
  UAE: 9,
};
export const UNITS = {
  KG: 1,
  MTR: 2,
  NOS: 3,
  SET: 4,
  PCS: 5,
  LTR: 6,
};

export const VENDOR_PRIORITY = {
  LOW: 1,
  MEDIUM: 2,
  HIGH: 3,
};

export const MATERIAL_STAGES = {
  AVAILABLE: 1,
  PURCHASE: 2,
  RECEIVED: 3,
  IQC_COMPLETED: 4,
  PRODUCTION_STARTED: 5,
  PRODUCTION_COMPLETED: 6,
  TESTED_AND_APPROVED: 7,
};
export const ITEM_STATUS = {
  AVAILABLE: 1,
  ASSIGNED: 2,
};
export const APP_TYPES = {
  WEB: 1,
  APP: 2,
};

export const QC_BUTTON_FILTER = {
  ALL: 1,
  PASSED: 2,
  QC_PENDING: 3,
  REJECTED: 4,
};

export const MODES = {
  "0b": 0,
  "0c": 1,
  "0d": 2,
  "0e": 3,
};

export const VOLUME_COMMANDS_REVERSE = {
  10: 0,
  11: 2,
  12: 4,
  13: 6,
  14: 8,
  15: 10,
  16: 12,
  17: 14,
  18: 16,
  19: 18,
  "1a": 20,
  "1b": 22,
  "1c": 24,
  "1d": 26,
  "1e": 28,
  "1f": 30,
};

export const EQ_LEVEL = [20, 30, 70, 50, 60];

export const ITE_MODE = {
  "01": 0,
  "02": 1,
  "03": 2,
  "04": 3,
};
